const arrowDown = "hotspot-arrow hotspot-arrow-down";
const arrowUp = "hotspot-arrow hotspot-arrow-up";
const arrowRight = "hotspot-arrow hotspot-arrow-right";
const arrowRight2 = "hotspot-arrow hotspot-arrow-right-2";
const arrowLeft = "hotspot-arrow hotspot-arrow-left";
const arrowPoint = "hotspot-arrow hotspot-arrow-point";
const panoramaConfig = {
  id: "panorama",
  data: {
    default: {
      firstScene: "ruhu",
      author: "常熟零距离房产",
      sceneFadeDuration: 1000,
      autoLoad: true,
      hotSpotDebug: true,
      autoRotate: -2,
      compass: true,
    },
    scenes: {
      ruhu: {
        title: "入户",
        hfov: 110,
        pitch: -2,
        yaw: 145,
        type: "equirectangular",
        panorama: require("@/assets/panorama/textures/rh.jpg"),
        hotSpots: [
          {
            pitch: -14,
            yaw: 45,
            type: "scene",
            text: "客厅",
            sceneId: "keting",
            cssClass: arrowDown,
          },
          {
            pitch: -21,
            yaw: 82,
            type: "scene",
            text: "次卧",
            sceneId: "ciwo",
            cssClass: arrowDown,
          },
          {
            pitch: -29,
            yaw: -89,
            type: "scene",
            text: "厨房",
            sceneId: "chufang",
            cssClass: arrowRight,
          },
          {
            pitch: -9,
            yaw: 55,
            type: "scene",
            text: "阳台",
            sceneId: "yangtai",
            cssClass: arrowUp,
          },
        ],
      },
      canting: {
        title: "餐厅",
        hfov: 110,
        pitch: -27,
        yaw: -91,
        type: "equirectangular",
        panorama: require("@/assets/panorama/textures/ct.jpg"),
        hotSpots: [
          {
            pitch: -15,
            yaw: -34,
            type: "scene",
            text: "客厅",
            sceneId: "keting",
            cssClass: arrowDown,
          },
          {
            pitch: -33,
            yaw: 172,
            type: "scene",
            text: "厨房",
            sceneId: "chufang",
            cssClass: arrowDown,
          },
          {
            pitch: -10,
            yaw: -16,
            type: "scene",
            text: "阳台",
            sceneId: "yangtai",
            cssClass: arrowUp,
          },
          {
            pitch: -24,
            yaw: 17,
            type: "scene",
            text: "入户",
            sceneId: "ruhu",
            cssClass: arrowRight,
          },
        ],
      },
      chufang: {
        title: "厨房",
        hfov: 110,
        pitch: -27,
        yaw: -123,
        type: "equirectangular",
        panorama: require("@/assets/panorama/textures/cf.jpg"),
        hotSpots: [
          {
            pitch: -22,
            yaw: 80,
            type: "scene",
            text: "入户",
            sceneId: "ruhu",
            cssClass: arrowLeft,
          },
          {
            pitch: -29,
            yaw: 11,
            type: "scene",
            text: "餐厅",
            sceneId: "canting",
            cssClass: arrowPoint,
          },
          {
            pitch: -7,
            yaw: -1,
            type: "scene",
            text: "客厅",
            sceneId: "keting",
            cssClass: arrowDown,
          },
          {
            pitch: -13,
            yaw: 24,
            type: "scene",
            text: "次卧",
            sceneId: "ciwo",
            cssClass: arrowRight2,
          },
        ],
      },
      ciwei: {
        title: "次卫",
        hfov: 110,
        pitch: -9,
        yaw: 150,
        type: "equirectangular",
        panorama: require("@/assets/panorama/textures/cw2.jpg"),
        hotSpots: [
          {
            pitch: -27,
            yaw: 3,
            type: "scene",
            text: "过道",
            sceneId: "guodao",
            cssClass: arrowDown,
          },
          {
            pitch: -7,
            yaw: 7,
            type: "scene",
            text: "客厅",
            sceneId: "keting",
            cssClass: arrowPoint,
          },
        ],
      },
      ciwo: {
        title: "次卧",
        hfov: 110,
        pitch: -1,
        yaw: -130,
        type: "equirectangular",
        panorama: require("@/assets/panorama/textures/cw.jpg"),
        hotSpots: [
          {
            pitch: -13,
            yaw: 2,
            type: "scene",
            text: "入户",
            sceneId: "ruhu",
            cssClass: arrowDown,
          },
          {
            pitch: -21,
            yaw: 8,
            type: "scene",
            text: "客厅",
            sceneId: "keting",
            cssClass: arrowRight,
          },
        ],
      },
      ertongfang: {
        title: "儿童房",
        hfov: 110,
        pitch: -10,
        yaw: -161,
        type: "equirectangular",
        panorama: require("@/assets/panorama/textures/etf.jpg"),
        hotSpots: [
          {
            pitch: -21,
            yaw: -3,
            type: "scene",
            text: "过道",
            sceneId: "guodao",
            cssClass: arrowDown,
          },
          {
            pitch: -7,
            yaw: -1,
            type: "scene",
            text: "客厅",
            sceneId: "keting",
            cssClass: arrowPoint,
          },
        ],
      },
      guodao: {
        title: "过道",
        hfov: 110,
        pitch: 9,
        yaw: 180,
        type: "equirectangular",
        panorama: require("@/assets/panorama/textures/gd.jpg"),
        hotSpots: [
          {
            pitch: -43,
            yaw: -150,
            type: "scene",
            text: "主卧",
            sceneId: "zhuwo",
            cssClass: arrowRight,
          },
          {
            pitch: -35,
            yaw: 30,
            type: "scene",
            text: "次卫",
            sceneId: "ciwei",
            cssClass: arrowRight2,
          },
          {
            pitch: -17,
            yaw: 10,
            type: "scene",
            text: "客厅",
            sceneId: "keting",
            cssClass: arrowRight,
          },
          {
            pitch: -8,
            yaw: 5,
            type: "scene",
            text: "入户",
            sceneId: "ruhu",
            cssClass: arrowRight,
          },
          {
            pitch: -8,
            yaw: -2,
            type: "scene",
            text: "次卧",
            sceneId: "ciwo",
            cssClass: arrowLeft,
          },
          {
            pitch: -11,
            yaw: -36,
            type: "scene",
            text: "客厅",
            sceneId: "keting",
            cssClass: arrowDown,
          },
        ],
      },
      keting: {
        title: "客厅",
        hfov: 110,
        pitch: -12,
        yaw: 153,
        type: "equirectangular",
        panorama: require("@/assets/panorama/textures/kt.jpg"),
        hotSpots: [
          {
            pitch: -8,
            yaw: -20,
            type: "scene",
            text: "厨房",
            sceneId: "chufang",
            cssClass: arrowUp,
          },
          {
            pitch: -10,
            yaw: -5,
            type: "scene",
            text: "餐厅",
            sceneId: "canting",
            cssClass: arrowDown,
          },
          {
            pitch: -19,
            yaw: -61,
            type: "scene",
            text: "次卧",
            sceneId: "ciwo",
            cssClass: arrowLeft,
          },
          {
            pitch: -13,
            yaw: -52,
            type: "scene",
            text: "入户",
            sceneId: "ruhu",
            cssClass: arrowRight2,
          },
          {
            pitch: -17,
            yaw: -177,
            type: "scene",
            text: "阳台",
            sceneId: "yangtai",
            cssClass: arrowDown,
          },
          {
            pitch: -12,
            yaw: 30,
            type: "scene",
            text: "次卫",
            sceneId: "ciwei",
            cssClass: arrowPoint,
          },
          {
            pitch: -9,
            yaw: 47,
            type: "scene",
            text: "儿童房",
            sceneId: "ertongfang",
            cssClass: arrowPoint,
          },
          {
            pitch: -13,
            yaw: 65,
            type: "scene",
            text: "主卧",
            sceneId: "zhuwo",
            cssClass: arrowRight,
          },
        ],
      },
      yangtai: {
        title: "阳台",
        hfov: 110,
        pitch: -24,
        yaw: -4,
        type: "equirectangular",
        panorama: require("@/assets/panorama/textures/yt.jpg"),
        hotSpots: [
          {
            pitch: -19,
            yaw: -76,
            type: "scene",
            text: "客厅",
            sceneId: "keting",
            cssClass: arrowDown,
          },
          {
            pitch: -13,
            yaw: -116,
            type: "scene",
            text: "入户",
            sceneId: "ruhu",
            cssClass: arrowLeft,
          },
          {
            pitch: -9,
            yaw: -101,
            type: "scene",
            text: "厨房",
            sceneId: "chufang",
            cssClass: arrowUp,
          },
          {
            pitch: -7,
            yaw: -91,
            type: "scene",
            text: "餐厅",
            sceneId: "canting",
            cssClass: arrowDown,
          },
          {
            pitch: -6,
            yaw: -74,
            type: "scene",
            text: "次卫",
            sceneId: "ciwei",
            cssClass: arrowPoint,
          },
          {
            pitch: -4,
            yaw: -65,
            type: "scene",
            text: "儿童房",
            sceneId: "ertongfang",
            cssClass: arrowPoint,
          },
        ],
      },
      zhuwei: {
        title: "主卫",
        hfov: 110,
        pitch: -27,
        yaw: -129,
        type: "equirectangular",
        panorama: require("@/assets/panorama/textures/zw.jpg"),
        hotSpots: [
          {
            pitch: -12,
            yaw: 2,
            type: "scene",
            text: "主卧",
            sceneId: "zhuwo",
            cssClass: arrowUp,
          },
          {
            pitch: -24,
            yaw: 4,
            type: "scene",
            text: "主卧衣帽间",
            sceneId: "zhuwoyimaojian",
            cssClass: arrowDown,
          },
        ],
      },
      zhuwo: {
        title: "主卧",
        hfov: 110,
        pitch: -5,
        yaw: 129,
        type: "equirectangular",
        panorama: require("@/assets/panorama/textures/zw2.jpg"),
        hotSpots: [
          {
            pitch: -20,
            yaw: -7,
            type: "scene",
            text: "过道",
            sceneId: "guodao",
            cssClass: arrowDown,
          },
          {
            pitch: -19,
            yaw: 32,
            type: "scene",
            text: "主卧衣帽间",
            sceneId: "zhuwoyimaojian",
            cssClass: arrowDown,
          },
        ],
      },
      zhuwoyimaojian: {
        title: "主卧衣帽间",
        hfov: 110,
        pitch: -2,
        yaw: 167,
        type: "equirectangular",
        panorama: require("@/assets/panorama/textures/zwymj.jpg"),
        hotSpots: [
          {
            pitch: -26,
            yaw: 130,
            type: "scene",
            text: "主卫",
            sceneId: "zhuwei",
            cssClass: arrowDown,
          },
          {
            pitch: -15,
            yaw: -37,
            type: "scene",
            text: "主卧",
            sceneId: "zhuwo",
            cssClass: arrowDown,
          },
        ],
      },
    },
  },
};
const menuFontUrl = "./static/fonts/zhfyh.json";
const menuFontConfig = {
  size: 3,
  height: 0.4,
  curveSegments: 24,
  bevelEnabled: true,
  bevelThickness: 0.5,
  bevelSize: 0.1,
  bevelSegments: 10,
};
export { panoramaConfig, menuFontUrl, menuFontConfig };
