const panoramaConfig = {
  id: "panorama",
  data: {
    default: {
      firstScene: "ruhu",
      author: "常熟零距离房产",
      sceneFadeDuration: 1000,
      autoLoad: true,
      hotSpotDebug: true,
    },
    scenes: {
      ruhu: {
        title: "入户",
        hfov: 110,
        pitch: -3,
        yaw: 117,
        type: "equirectangular",
        panorama: require("@/assets/textures/rh.jpg"),
        hotSpots: [
          {
            pitch: -14,
            yaw: 45,
            type: "scene",
            text: "客厅",
            sceneId: "keting",
            cssClass: "hotspot-arrow hotspot-arrow-down",
          },
          {
            pitch: -21,
            yaw: 82,
            type: "scene",
            text: "次卧",
            sceneId: "ciwo",
            cssClass: "hotspot-arrow hotspot-arrow-down",
          },
          {
            pitch: -29,
            yaw: -89,
            type: "scene",
            text: "厨房",
            sceneId: "chufang",
            cssClass: "hotspot-arrow hotspot-arrow-right",
          },
          {
            pitch: -9,
            yaw: 55,
            type: "scene",
            text: "阳台",
            sceneId: "yangtai",
            cssClass: "hotspot-arrow hotspot-arrow-up",
          },
        ],
      },
      canting: {
        title: "餐厅",
        hfov: 110,
        pitch: -3,
        yaw: 117,
        type: "equirectangular",
        panorama: require("@/assets/textures/ct.jpg"),
        hotSpots: [
          {
            pitch: -12.1,
            yaw: 340.9,
            type: "scene",
            text: "客厅",
            sceneId: "keting",
          },
          {
            pitch: -42.1,
            yaw: 180.9,
            type: "scene",
            text: "厨房",
            sceneId: "chufang",
          },
        ],
      },
      chufang: {
        title: "厨房",
        hfov: 110,
        pitch: -3,
        yaw: 117,
        type: "equirectangular",
        panorama: require("@/assets/textures/cf.jpg"),
        hotSpots: [
          {
            pitch: -22.1,
            yaw: 82.9,
            type: "scene",
            text: "入户",
            sceneId: "ruhu",
          },
          {
            pitch: -30.1,
            yaw: 0.9,
            type: "scene",
            text: "餐厅",
            sceneId: "canting",
          },
          {
            pitch: -0.1,
            yaw: -10.9,
            type: "scene",
            text: "客厅",
            sceneId: "keting",
          },
        ],
      },
      keting: {
        title: "客厅",
        hfov: 110,
        yaw: 5,
        type: "equirectangular",
        panorama: require("@/assets/textures/kt.jpg"),
        hotSpots: [
          {
            pitch: -0.6,
            yaw: -20.0,
            type: "scene",
            text: "餐厅",
            sceneId: "canting",
            targetYaw: -23,
            targetPitch: 2,
          },
          {
            pitch: -10.6,
            yaw: 180.0,
            type: "scene",
            text: "阳台",
            sceneId: "yangtai",
            targetYaw: -23,
            targetPitch: 2,
          },
        ],
      },
      ciwo: {
        title: "次卧",
        hfov: 110,
        pitch: -3,
        yaw: 117,
        type: "equirectangular",
        panorama: require("@/assets/textures/cw.jpg"),
        hotSpots: [
          {
            pitch: -30.1,
            yaw: 2.9,
            type: "scene",
            text: "入户",
            sceneId: "ruhu",
          },
        ],
      },
      yangtai: {
        title: "阳台",
        hfov: 110,
        pitch: -3,
        yaw: 117,
        type: "equirectangular",
        panorama: require("@/assets/textures/yt.jpg"),
        hotSpots: [
          {
            pitch: -22.1,
            yaw: -80.9,
            type: "scene",
            text: "客厅",
            sceneId: "keting",
          },
        ],
      },
    },
  },
};
export { panoramaConfig };
