const arrowDown = "hotspot-arrow hotspot-arrow-down";
const arrowUp = "hotspot-arrow hotspot-arrow-up";
const arrowRight = "hotspot-arrow hotspot-arrow-right";
const arrowRight2 = "hotspot-arrow hotspot-arrow-right-2";
const arrowLeft = "hotspot-arrow hotspot-arrow-left";
const arrowPoint = "hotspot-arrow hotspot-arrow-point";
const panoramaConfig = {
  id: "panorama",
  data: {
    default: {
      firstScene: "ruhu",
      author: "常熟零距离房产",
      sceneFadeDuration: 1000,
      autoLoad: true,
      hotSpotDebug: true,
    },
    scenes: {
      ruhu: {
        title: "入户",
        hfov: 110,
        pitch: -2,
        yaw: 145,
        type: "equirectangular",
        panorama: require("@/assets/textures/rh.jpg"),
        hotSpots: [
          {
            pitch: -14,
            yaw: 45,
            type: "scene",
            text: "客厅",
            sceneId: "keting",
            cssClass: arrowDown,
          },
          {
            pitch: -21,
            yaw: 82,
            type: "scene",
            text: "次卧",
            sceneId: "ciwo",
            cssClass: arrowDown,
          },
          {
            pitch: -29,
            yaw: -89,
            type: "scene",
            text: "厨房",
            sceneId: "chufang",
            cssClass: arrowRight,
          },
          {
            pitch: -9,
            yaw: 55,
            type: "scene",
            text: "阳台",
            sceneId: "yangtai",
            cssClass: arrowUp,
          },
        ],
      },
      canting: {
        title: "餐厅",
        hfov: 110,
        pitch: -27,
        yaw: -91,
        type: "equirectangular",
        panorama: require("@/assets/textures/ct.jpg"),
        hotSpots: [
          {
            pitch: -15,
            yaw: -34,
            type: "scene",
            text: "客厅",
            sceneId: "keting",
            cssClass: arrowDown,
          },
          {
            pitch: -33,
            yaw: 172,
            type: "scene",
            text: "厨房",
            sceneId: "chufang",
            cssClass: arrowDown,
          },
          {
            pitch: -10,
            yaw: -16,
            type: "scene",
            text: "阳台",
            sceneId: "yangtai",
            cssClass: arrowUp,
          },
          {
            pitch: -24,
            yaw: 17,
            type: "scene",
            text: "入户",
            sceneId: "ruhu",
            cssClass: arrowRight,
          },
        ],
      },
      chufang: {
        title: "厨房",
        hfov: 110,
        pitch: -27,
        yaw: -123,
        type: "equirectangular",
        panorama: require("@/assets/textures/cf.jpg"),
        hotSpots: [
          {
            pitch: -22,
            yaw: 80,
            type: "scene",
            text: "入户",
            sceneId: "ruhu",
            cssClass: arrowLeft,
          },
          {
            pitch: -29,
            yaw: 11,
            type: "scene",
            text: "餐厅",
            sceneId: "canting",
            cssClass: arrowPoint,
          },
          {
            pitch: -7,
            yaw: -1,
            type: "scene",
            text: "客厅",
            sceneId: "keting",
            cssClass: arrowDown,
          },
          {
            pitch: -13,
            yaw: 24,
            type: "scene",
            text: "次卧",
            sceneId: "ciwo",
            cssClass: arrowRight2,
          },
        ],
      },
      keting: {
        title: "客厅",
        hfov: 110,
        pitch: -12,
        yaw: 153,
        type: "equirectangular",
        panorama: require("@/assets/textures/kt.jpg"),
        hotSpots: [
          {
            pitch: -8,
            yaw: -20,
            type: "scene",
            text: "厨房",
            sceneId: "chufang",
            cssClass: arrowUp,
          },
          {
            pitch: -10,
            yaw: -5,
            type: "scene",
            text: "餐厅",
            sceneId: "canting",
            cssClass: arrowDown,
          },
          {
            pitch: -19,
            yaw: -61,
            type: "scene",
            text: "次卧",
            sceneId: "ciwo",
            cssClass: arrowLeft,
          },
          {
            pitch: -13,
            yaw: -52,
            type: "scene",
            text: "入户",
            sceneId: "ruhu",
            cssClass: arrowRight2,
          },
          {
            pitch: -17,
            yaw: -177,
            type: "scene",
            text: "阳台",
            sceneId: "yangtai",
            cssClass: arrowDown,
          },
        ],
      },
      ciwo: {
        title: "次卧",
        hfov: 110,
        pitch: -1,
        yaw: -130,
        type: "equirectangular",
        panorama: require("@/assets/textures/cw.jpg"),
        hotSpots: [
          {
            pitch: -13,
            yaw: 2,
            type: "scene",
            text: "入户",
            sceneId: "ruhu",
            cssClass: arrowDown,
          },
          {
            pitch: -21,
            yaw: 8,
            type: "scene",
            text: "客厅",
            sceneId: "keting",
            cssClass: arrowRight,
          },
        ],
      },
      yangtai: {
        title: "阳台",
        hfov: 110,
        pitch: -24,
        yaw: -4,
        type: "equirectangular",
        panorama: require("@/assets/textures/yt.jpg"),
        hotSpots: [
          {
            pitch: -19,
            yaw: -76,
            type: "scene",
            text: "客厅",
            sceneId: "keting",
            cssClass: arrowDown,
          },
          {
            pitch: -13,
            yaw: -116,
            type: "scene",
            text: "入户",
            sceneId: "ruhu",
            cssClass: arrowLeft,
          },
          {
            pitch: -9,
            yaw: -101,
            type: "scene",
            text: "厨房",
            sceneId: "chufang",
            cssClass: arrowUp,
          },
          {
            pitch: -7,
            yaw: -91,
            type: "scene",
            text: "餐厅",
            sceneId: "canting",
            cssClass: arrowDown,
          },
        ],
      },
    },
  },
};
export { panoramaConfig };
